services:
  - type: web
    name: bookai-app
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18